also apply kubelet serving cert appropriately

diff --git a/assets/v4.2.0/ca-operator/ca-operator-deployment.yaml b/assets/v4.2.0/ca-operator/ca-operator-deployment.yaml
--- a/assets/v4.2.0/ca-operator/ca-operator-deployment.yaml
+++ b/assets/v4.2.0/ca-operator/ca-operator-deployment.yaml
@@ -61,8 +61,26 @@ spec:
           #!/bin/bash
           set -e
           while(true); do
-            # Use the internal cluster's kubeconfig to collect router and service CA
+            # Use the internal cluster's kubeconfig to collect router and service CA and apply kubelet serving ca configmap
             export KUBECONFIG=/etc/kubernetes/kubeconfig/kubeconfig
+          cat > /tmp/kubelet-serving-ca-configmap.json <<EOF
+          {
+              "apiVersion": "v1",
+              "data": {
+                "ca-bundle.crt": "$(awk -v ORS='\\n' '1' /etc/kubernetes/config/initial-ca.crt)"
+              },
+              "kind": "ConfigMap",
+              "metadata": {
+                    "name": "kubelet-serving-ca",
+                    "namespace": "openshift-config-managed"
+                }
+          }
+          EOF
+            if ! oc apply -f /tmp/kubelet-serving-ca-configmap.json; then
+               echo "Could not apply kubelet serving ca yet. Will continue to wait"
+               sleep 30
+               continue
+            fi
             if ! oc get cm -n openshift-config-managed router-ca -o jsonpath='{ .data.ca-bundle\.crt }' > /tmp/router.ca; then
                echo "Cannot fetch router-ca yet. Will continue to wait"
                sleep 30
