Update for master (#36)
* Properly configure the APIServices for openshift (#13)

* switch to old cvo operator

* update release

* update

* update data

* update with ca bundle for openshift apiservice

* Ca operator (#14)

* add ca-operator

* cli image

* Cloud provider (#18) (#19)

* Properly configure the APIServices for openshift (#13)

* switch to old cvo operator

* update release

* update

* update data

* update with ca bundle for openshift apiservice

* Ca operator (#14)

* add ca-operator

* cli image

* apiserver config additions

* make cloud provider a variable

* new line

(cherry picked from commit 55b9b4731be40a9abba8d9b84efe59ac07201824)

* needed label for openvpn operator

* needed label for openvpn operator (#20)

* update assets with namespace (#21)

* fix ca-operator and variables

* wrong spot

* wrong spot

* use json patch instead

* formatt

* cleanup

* fix ca-operator and variables (#22)

* needed label for openvpn operator

* fix ca-operator and variables

* wrong spot

* wrong spot

* use json patch instead

* formatt

* cleanup

* rename

* Rename file to not conflict with CO CRD (#23)

* needed label for openvpn operator

* fix ca-operator and variables

* wrong spot

* wrong spot

* use json patch instead

* formatt

* cleanup

* rename

* Fix oauth server and properly allow toggle between external and internal oauth server (#24)

* update oauth server

* fix oauth server

* also apply kubelet serving cert appropriately

* add configuration to init container (#25)

* Add owners (#27)

* Fix owners (#29)

* Add make verify (#31)

* add internal api port  (#32)

* update

* update asset data

* Fix port specification logic (#33)

* update

* update asset data

* update port specification

* add ability to specify advertised port

* update port specification

* update port specification

* Remove asset versioning (#34)

* needed label for openvpn operator

* fix ca-operator and variables

* wrong spot

* wrong spot

* use json patch instead

* formatt

* cleanup

* rename

* remove asset versioning. Versioning will be done at the branch level now instead

* remove more v420 assets

* use other cvo

diff --git a/assets/ca-operator/ca-operator-deployment.yaml b/assets/ca-operator/ca-operator-deployment.yaml
--- a/assets/ca-operator/ca-operator-deployment.yaml
+++ b/assets/ca-operator/ca-operator-deployment.yaml
@@ -61,8 +61,26 @@ spec:
           #!/bin/bash
           set -e
           while(true); do
-            # Use the internal cluster's kubeconfig to collect router and service CA
+            # Use the internal cluster's kubeconfig to collect router and service CA and apply kubelet serving ca configmap
             export KUBECONFIG=/etc/kubernetes/kubeconfig/kubeconfig
+          cat > /tmp/kubelet-serving-ca-configmap.json <<EOF
+          {
+              "apiVersion": "v1",
+              "data": {
+                "ca-bundle.crt": "$(awk -v ORS='\\n' '1' /etc/kubernetes/config/initial-ca.crt)"
+              },
+              "kind": "ConfigMap",
+              "metadata": {
+                    "name": "kubelet-serving-ca",
+                    "namespace": "openshift-config-managed"
+                }
+          }
+          EOF
+            if ! oc apply -f /tmp/kubelet-serving-ca-configmap.json; then
+               echo "Could not apply kubelet serving ca yet. Will continue to wait"
+               sleep 30
+               continue
+            fi
             if ! oc get cm -n openshift-config-managed router-ca -o jsonpath='{ .data.ca-bundle\.crt }' > /tmp/router.ca; then
                echo "Cannot fetch router-ca yet. Will continue to wait"
                sleep 30
@@ -77,8 +95,19 @@ spec:
             CHECKSUM="$(python -c "import hashlib;print hashlib.md5(open('/tmp/kcm.ca').read()).hexdigest()")"
             # Switch to the management cluster and apply latest CA
             unset KUBECONFIG
-            export KCM_CA="$(cat /tmp/kcm.ca)"
-            oc patch cm kube-controller-manager --type=json --patch "[{\"op\": \"replace\", \"path\": \"/data/service-ca.crt\", \"value\":\"${KCM_CA}\"}]"
+          cat > /tmp/patch_ca.json <<EOF
+          {
+              "apiVersion": "v1",
+              "data": {
+                "service-ca.crt": "$(awk -v ORS='\\n' '1' /tmp/kcm.ca)"
+              },
+              "kind": "ConfigMap",
+              "metadata": {
+                  "name": "kube-controller-manager"
+              }
+          }
+          EOF
+            oc patch cm kube-controller-manager --patch "$(cat /tmp/patch_ca.json)"
             oc patch deployment kube-controller-manager  --type=json --patch "[{\"op\": \"replace\", \"path\": \"/spec/template/metadata/annotations\", \"value\":{\"ca-checksum\":\"${CHECKSUM}\"}}]"
             sleep 30
           done
